# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Publish

on:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  publish-wp-json-schemas:
    name: Publish wp-json-schemas
    runs-on: ubuntu-latest
    permissions:
      contents: read # To read the repository
      id-token: write # OIDC token for trusted publishing
    environment:
      name: wp-json-schemas
      url: https://www.npmjs.com/package/wp-json-schemas
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Deploy to npm using trusted publishing with OIDC
        run: npm publish --access public

  publish-wp-types:
    name: Publish wp-types
    runs-on: ubuntu-latest
    permissions:
      contents: read # To read the repository
      id-token: write # OIDC token for trusted publishing
    environment:
      name: wp-types
      url: https://www.npmjs.com/package/wp-types
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Deploy to npm using trusted publishing with OIDC
        run: |
          cd packages/wp-types
          npm install
          npm publish --access public
