# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Publish

on:
  push:
    tags:
      - '*'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish-wp-json-schemas:
    name: Publish wp-json-schemas
    runs-on: ubuntu-latest
    permissions:
      contents: read  # To read the repository
      id-token: write # OIDC token for trusted publishing
    environment:
      name: wp-json-schemas
      url: https://www.npmjs.com/package/wp-json-schemas
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci --no-audit --no-fund --ignore-scripts

      - name: Deploy to npm using trusted publishing with OIDC
        run: npm publish --access public

  publish-wp-types:
    name: Publish wp-types
    runs-on: ubuntu-latest
    permissions:
      contents: read  # To read the repository
      id-token: write # OIDC token for trusted publishing
    environment:
      name: wp-types
      url: https://www.npmjs.com/package/wp-types
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Deploy to npm using trusted publishing with OIDC
        run: |
          cd packages/wp-types
          npm ci --no-audit --no-fund --ignore-scripts
          npm run build
          npm publish --access public

  github:
    name: GitHub Milestones
    permissions:
      issues: write # Required for write access to milestones
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-milestones.yml@407e1d8405b366f95664ce4ec62127eb9ecad808 # 2.9.0
    with:
      version: ${{ github.ref_name }}
