# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  publish-wp-json-schemas:
    runs-on: ubuntu-latest
    environment:
      name: wp-json-schemas
      url: https://www.npmjs.com/package/wp-json-schemas
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-wp-types:
    runs-on: ubuntu-latest
    environment:
      name: wp-types
      url: https://www.npmjs.com/package/wp-types
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: Deploy to npm
        run: |
          cd packages/wp-types
          npm ci
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
