# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Lint workflow files
on:
  pull_request:
    paths:
      # Only run when changes are made to workflow files.
      - '.github/workflows/**'
  push:
    branches:
      - develop
      - trunk
    paths:
      # Only run when changes are made to workflow files.
      - '.github/workflows/**'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    permissions:
      security-events: write # To upload results to CodeQL
      actions: read          # To read workflow runs
      contents: read         # To read the repository
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-workflow-lint.yml@9a6405c89f3357947cd8f608bdc72d68fe17f4ae # v2.1.2
