# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test

on:
  push:
    branches:
      - 'develop'
      - 'trunk'
  pull_request:
    branches:
      - '**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Codebase
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read # To read the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Composer cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-8.0-composer-${{ hashFiles('composer.json') }}

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'

      - name: Install PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: 8.0
          extensions: xmlwriter
          coverage: none
        env:
          fail-fast: true

      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
          npm --version
          node --version

      - name: Install Node dependencies
        run: npm ci --no-audit --no-fund --ignore-scripts

      - name: Install Composer dependencies
        run: composer install

      - name: Run tests
        run: composer run test

      - name: Check for changes
        run: git diff --exit-code
